/**
 * @file test_test_divergence_sync_standalone_mode3c.cpp
 * @brief Mode 3C: Standalone binary end-to-end execution (FAIL reproduction)
 *
 * Auto-generated by four-mode testing generator.
 * Runs the standalone binary and checks if it produces FAIL output.
 * When the underlying bug is fixed, the standalone binary will output PASS,
 * and this test must be updated to expect PASS.
 *
 * NOTE: Mode 3C does NOT depend on internal PtxContext or GPUContext types
 * (which have X-macro conflicts with ptx_parser.h / ptx_types.h).
 * Instead it uses popen() to run the real compiled binary.
 */

#include "catch_amalgamated.hpp"
#include <cstdio>
#include <string>

#ifndef TEST_BINARY
#define TEST_BINARY "build/bin/test_divergence_sync_standalone"
#endif

TEST_CASE("Mode3C: test_divergence_sync_standalone - standalone FAIL reproduction", "[mode3c][e2e]") {
    // 运行 standalone 二进制，捕获 stdout + stderr
    std::string cmd = "PTX_LOG_LEVEL=error LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH "
                      "timeout 15 "
                      TEST_BINARY " 2>&1";
    FILE* pipe = popen(cmd.c_str(), "r");
    REQUIRE(pipe != nullptr);

    std::string output;
    char buf[1024];
    while (fgets(buf, sizeof(buf), pipe)) {
        output += buf;
    }
    int ret = pclose(pipe);

    INFO("Standalone binary output (" << output.size() << " bytes):");
    INFO(output);

    // 检测 FAIL 标记
    bool has_fail = output.find("=== Result: FAIL ===") != std::string::npos;
    bool has_pass = output.find("=== Result: PASS ===") != std::string::npos;

    INFO("Has FAIL: " << has_fail << ", Has PASS: " << has_pass);

    // 当前复现 FAIL：standalone 输出 FAIL
    // 当 bug 修复后，has_pass 应为 true，has_fail 应为 false
    CHECK(has_fail);
    CHECK(!has_pass);
}

// ============================================================================
// Custom test cases - add kernel-specific expected values here
// ============================================================================
