#ifndef PTXSIM_INSTRUCTION_HANDLERS_H
#define PTXSIM_INSTRUCTION_HANDLERS_H

#include "ptxsim/instruction_base.h"
#include "ptx_ir/statement_context.h"
#include <string>
#include <vector>

// Declaration handlers
#define DECLARE_DECLARATION_HANDLER(Name) \
    class Name##Handler : public DeclarationHandler { \
    public: \
        void ExecPipe(ThreadContext *context, StatementContext &stmt) override; \
    };

#define DECLARE_OPERAND_REG_HANDLER(Name)     DECLARE_DECLARATION_HANDLER(Name)
#define DECLARE_OPERAND_CONST_HANDLER(Name)   DECLARE_DECLARATION_HANDLER(Name)
#define DECLARE_OPERAND_MEMORY_HANDLER(Name)  DECLARE_DECLARATION_HANDLER(Name)

// Simple handlers
#define DECLARE_SIMPLE_HANDLER(Name) \
    class Name##Handler : public SimpleHandler { \
    public: \
        void ExecPipe(ThreadContext *context, StatementContext &stmt) override; \
    };

#define DECLARE_SIMPLE_NAME_HANDLER(Name)     DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_LABEL_INSTR_HANDLER(Name)     DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_SIMPLE_STRING_HANDLER(Name)   DECLARE_SIMPLE_HANDLER(Name)

// Void handlers
#define DECLARE_VOID_HANDLER(Name) \
    class Name##Handler : public VoidHandler { \
    public: \
        void ExecPipe(ThreadContext *context, StatementContext &stmt) override; \
        virtual void processOperation(ThreadContext *context, StatementContext &stmt); \
    };

// All VOID_INSTR handlers will be generated by the macro below
#define DECLARE_VOID_INSTR_HANDLER(Name) \
    class Name##Handler : public VoidHandler { \
    public: \
        void ExecPipe(ThreadContext *context, StatementContext &stmt) override; \
        virtual void processOperation(ThreadContext *context, StatementContext &stmt); \
    };

// Branch handlers
#define DECLARE_BRANCH_HANDLER(Name) \
    class Name##Handler : public BranchHandler { \
    public: \
        void executeBranch(ThreadContext *context, const BranchInstr &instr) override; \
    };

// Barrier handlers — FIXED: must override pure virtual
#define DECLARE_BARRIER_HANDLER(Name) \
    class Name##Handler : public BarrierHandler { \
    public: \
        void executeBarrier(ThreadContext *context, const BarrierInstr &instr) override; \
    };

// Warp barrier handlers - need to override prepare/execute/commit for BarWarpSyncInstr
#define DECLARE_WARP_BARRIER_HANDLER(Name) \
    class Name##Handler : public GenericPipelineHandler { \
    public: \
        bool prepareOperands(ThreadContext *context, StatementContext &stmt) override; \
        bool executeOperation(ThreadContext *context, StatementContext &stmt) override; \
        bool commitResults(ThreadContext *context, StatementContext &stmt) override; \
        void processOperation(ThreadContext *context, void **operands, \
                             const std::vector<Qualifier> &qualifiers, \
                             const std::vector<char> *operand_is_immediate = nullptr) override; \
    };

// Call handlers — FIXED: declare all used methods
#define DECLARE_CALL_INSTR_HANDLER(Name) \
    class Name##Handler : public CallBaseHandler { \
    public: \
        void executeCall(ThreadContext *context, const CallInstr &instr) override; \
        void handlePrintf(ThreadContext *context, const CallInstr &instr); \
        void parseAndPrintFormat(ThreadContext *context, const std::string &format, \
                                const std::vector<void *> &args); \
    };

// Generic instruction handlers — RECOMMENDED: declare override
#define DECLARE_GENERIC_INSTR_HANDLER(Name) \
    class Name##Handler : public GenericPipelineHandler { \
    public: \
        void processOperation(ThreadContext *context, void **operands, \
                             const std::vector<Qualifier> &qualifiers, \
                             const std::vector<char> *operand_is_immediate = nullptr) override; \
    };

// Atomic instruction handlers — RECOMMENDED
#define DECLARE_ATOM_INSTR_HANDLER(Name) \
    class Name##Handler : public AtomicPipelineHandler { \
    public: \
        void processAtomicOperation(ThreadContext *context, void **operands, \
                                   const std::vector<Qualifier> &qualifiers, \
                                   const std::vector<char> *operand_is_immediate = nullptr) override; \
    };

// WMMA instruction handlers — RECOMMENDED
#define DECLARE_WMMA_INSTR_HANDLER(Name) \
    class Name##Handler : public WmmaPipelineHandler { \
    public: \
        void processWmmaOperation(ThreadContext *context, void **operands, \
                                 const std::vector<Qualifier> &qualifiers) override; \
    };

// CP_ASYNC should use AsyncCopyHandler
#define DECLARE_CP_ASYNC_INSTR_HANDLER(Name) \
    class Name##Handler : public AsyncCopyHandler { \
    public: \
        void executeAsyncCopy(ThreadContext *context, const CpAsyncInstr &instr) override; \
    };

// Tcgen05: 11 X-Macro entries share a single Tcgen05Handler class
// (dispatched internally by instr.op_kind). Override the macro to be
// a no-op for the X-Macro expansion below; the real class is declared
// manually further down.
#define DECLARE_TCGEN05_INSTR_HANDLER(Name)  /* no-op: see below */

#define DECLARE_MEMBAR_INSTR_HANDLER(Name)     DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_FENCE_INSTR_HANDLER(Name)      DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_REDUX_INSTR_HANDLER(Name)      DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_MBARRIER_INSTR_HANDLER(Name)   DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_PREDICATE_PREFIX_HANDLER(Name) DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_VOTE_INSTR_HANDLER(Name)       DECLARE_SIMPLE_HANDLER(Name)
// DECLARE_WARP_BARRIER_HANDLER is defined separately above (line 62-68) - uses GenericPipelineHandler
#define DECLARE_SHFL_INSTR_HANDLER(Name)       DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_TEXTURE_INSTR_HANDLER(Name)    DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_SURFACE_INSTR_HANDLER(Name)    DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_REDUCTION_INSTR_HANDLER(Name)  DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_PREFETCH_INSTR_HANDLER(Name)   DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_ASYNC_STORE_HANDLER(Name)      DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_ASYNC_REDUCE_HANDLER(Name)     DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_TCGEN_INSTR_HANDLER(Name)      DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_TENSORMAP_INSTR_HANDLER(Name)  DECLARE_SIMPLE_HANDLER(Name)
#define DECLARE_ABI_DIRECTIVE_HANDLER(Name)    DECLARE_SIMPLE_HANDLER(Name)

// Generate all handler declarations
// Tcgen05 has 11 sub-op X entries that all share the same handler class
// (Tcgen05Handler dispatches by instr.op_kind internally). To avoid 11
// redefinition errors, the X-Macro skips TCGEN05_INSTR and we declare
// the single Tcgen05Handler class manually below.
#define X(enum_val, op_name, op_str, op_count, struct_kind, instr_kind) \
    DECLARE_##struct_kind##_HANDLER(op_str)
#include "ptx_ir/ptx_op.def"
#undef X
#undef DECLARE_TCGEN05_INSTR_HANDLER  // Clear the 11-times-expanded macro

// Manual single Tcgen05Handler class declaration (replaces the
// 11-times-expanded DECLARE_TCGEN05_INSTR_HANDLER that conflicted).
// Class is in GLOBAL namespace to match the X-Macro factory registration
// pattern (handler_map[S_TCGEN05_*] = new Tcgen05Handler()).
class Tcgen05Handler : public Tcgen05PipelineHandler {
public:
    void processTcgen05Operation(ThreadContext *context, void **operands,
                                 const std::vector<Qualifier> &qualifiers,
                                 const Tcgen05Instr &instr) override;
};

#endif // PTXSIM_INSTRUCTION_HANDLERS_H
