/**
 * @file test_test_divergence_sync_standalone_mode2.cpp
 * @brief Mode 2: Pre-extracted PTX File
 *
 * Auto-generated by four-mode testing generator.
 * Loads pre-extracted PTX from file for stable, reproducible testing.
 */

#include "catch_amalgamated.hpp"
#include "test_helpers.hpp"

#define TEST_MODE 2
#define TEST_NAME "test_divergence_sync_standalone"

#ifndef PTX_FILE
#define PTX_FILE "tests/three_mode_testing/ptx/test_divergence_sync_standalone.ptx"
#endif

TEST_CASE("Mode2: Load PTX file", "[mode2][load]") {
    std::string ptx = load_ptx_file(PTX_FILE);
    if (ptx.empty()) {
        SKIP("PTX file not found: " PTX_FILE);
    }
    CHECK_FALSE(ptx.empty());
    INFO("Loaded " << ptx.size() << " bytes");
}

TEST_CASE("Mode2: Parse PTX structure", "[mode2][parse]") {
    std::string ptx = load_ptx_file(PTX_FILE);
    if (ptx.empty()) SKIP("PTX file not available");

    bool has_entry = ptx_contains(ptx, ".entry");
    bool has_bar = ptx_contains(ptx, "bar.");
    bool has_shared = ptx_contains(ptx, ".shared") || ptx_contains(ptx, "ld.shared") || ptx_contains(ptx, "st.shared");

    INFO("entry: " << has_entry << ", barrier: " << has_bar << ", shared: " << has_shared);
    CHECK(has_entry);
}

TEST_CASE("Mode2: Analyze PTX instruction counts", "[mode2][analyze]") {
    std::string ptx = load_ptx_file(PTX_FILE);
    if (ptx.empty()) SKIP("PTX file not available");

    int bar_count = 0, ld_shared_count = 0, st_shared_count = 0, bra_count = 0;
    bool has_entry = ptx_contains(ptx, ".entry");
    std::istringstream iss(ptx);
    std::string line;
    while (std::getline(iss, line)) {
        if (line.find("bar.") != std::string::npos) bar_count++;
        if (line.find("ld.shared") != std::string::npos) ld_shared_count++;
        if (line.find("st.shared") != std::string::npos) st_shared_count++;
        if (line.find("bra") != std::string::npos) bra_count++;
    }

    INFO("bar.sync: " << bar_count << ", ld.shared: " << ld_shared_count
         << ", st.shared: " << st_shared_count << ", bra: " << bra_count);

    CHECK(has_entry);
}
