/**
 * @file test_test_warp_divergence_mode3b.cpp
 * @brief Mode 3b: StatementContext AFTER CFG (Final Execution Version)
 *
 * Auto-generated by four-mode testing generator.
 * Uses StatementContext AFTER CFG builder has run.
 * Key difference from Mode 3a: reconvergence_pc IS now set (by CFGBuilder).
 * This is the version that actually executes in the simulator.
 */

#include "catch_amalgamated.hpp"
#include "test_helpers.hpp"

#define TEST_MODE 3
#define TEST_NAME "test_warp_divergence"

#ifndef PTX_FILE
#define PTX_FILE "tests/three_mode_testing/ptx/test_warp_divergence.ptx"
#endif

#ifndef TEST_BINARY
#define TEST_BINARY "build/bin/test_warp_divergence"
#endif


TEST_CASE("Mode3b: test_warp_divergence - barrier via StatementContext (cta)", "[mode3b][barrier]") {
    init_factory_once();

    // 使用 StatementContext 构建 barrier 指令序列 (AFTER CFG)
    std::vector<StatementContext> stmts;
    stmts.push_back(make_bar_sync(0));
    stmts.push_back(make_exit());

    CHECK(stmts.size() == 2);
    CHECK(stmts[0].type == S_BAR);
    CHECK(stmts[0].instructionText.find("bar") != std::string::npos);

    // AFTER CFG: barrier 的 reconvergence_pc 应在 CFGBuilder 处理后设置
    INFO("Mode3b barrier StatementContext verified");
}

TEST_CASE("Mode3b: test_warp_divergence - barrier Wbar arrive and complete", "[mode3b][barrier]") {
    init_factory_once();

    WarpContext warp;
    std::vector<std::unique_ptr<ThreadContext>> threads;
    setup_warp(warp, threads, 32);
    reset_warp(warp);
    warp.set_active_mask(0xFFFFFFFF);

    // 验证 Wbar.init / arrive / is_complete 流程
    Wbar& wbar = warp.get_warp_state().wbars[0];
    wbar.init(0xFFFFFFFF, 1);

    for (int i = 0; i < 32; i++) {
        warp.get_warp_state().threads[i].is_blocked = true;
        warp.get_warp_state().threads[i].status = ThreadStatus::Blocked;
        wbar.arrive(i);
    }

    CHECK(wbar.is_complete() == true);
    warp.set_exec_mask(wbar.arrived_mask);

    for (int i = 0; i < 32; i++) {
        if ((wbar.arrived_mask & (1u << i)) && warp.get_warp_state().threads[i].is_active) {
            warp.set_thread_pc(i, 1);
            warp.get_warp_state().threads[i].is_blocked = false;
            warp.get_warp_state().threads[i].status = ThreadStatus::Active;
        }
    }

    warp.set_active_mask(wbar.arrived_mask);
    CHECK(count_at_pc(warp, 1) == 32);
    CHECK(count_active_lanes(warp) == 32);
}




TEST_CASE("Mode3b: test_warp_divergence - shared memory via StatementContext", "[mode3b][shared]") {
    init_factory_once();

    std::vector<StatementContext> stmts;
    stmts.push_back(make_ld_shared("%r1", "shared_data", "%r0"));
    stmts.push_back(make_st_shared("shared_data", "%r0", "%r2"));
    stmts.push_back(make_exit());

    CHECK(stmts.size() == 3);
    CHECK(stmts[0].type == S_LD);
    CHECK(stmts[0].instructionText.find("ld.shared") != std::string::npos);
    CHECK(stmts[1].type == S_ST);
    CHECK(stmts[1].instructionText.find("st.shared") != std::string::npos);
}


TEST_CASE("Mode3b: test_warp_divergence - divergence via StatementContext", "[mode3b][divergence]") {
    init_factory_once();

    std::vector<StatementContext> stmts;
    stmts.push_back(make_mov("%r1", "%tid.x"));
    stmts.push_back(make_setp_lt("%p1", "%r1", "16"));
    stmts.push_back(make_label("L_true"));
    stmts.push_back(make_add("%r2", "%r1", "1"));
    stmts.push_back(make_mov_imm("%r2", -1));
    stmts.push_back(make_label("L_join"));
    stmts.push_back(make_exit());

    CHECK(stmts.size() == 7);
    CHECK(stmts[1].type == S_SETP);
    CHECK(stmts[2].type == S_LABEL);

    StatementContext bra = make_bra_pred("L_join", "%p1", false);
    CHECK(bra.type == S_BRA);
    const auto& bra_data = std::get<BranchInstr>(bra.data);
    INFO("Mode3b branch reconvergence_pc: " << bra_data.reconvergence_pc);
}


// ============================================================================
// Custom test cases - add your kernel-specific tests here
// ============================================================================
