/**
 * @file test_test_warp_divergence_mode1.cpp
 * @brief Mode 1: cuobjdump Dynamic Extraction
 *
 * Auto-generated by four-mode testing generator.
 * Extracts PTX at runtime using cuobjdump.
 */

#include "catch_amalgamated.hpp"
#include "test_helpers.hpp"

#define TEST_MODE 1
#define TEST_NAME "test_warp_divergence"

#ifndef TEST_BINARY
#define TEST_BINARY "build/bin/test_warp_divergence"
#endif

TEST_CASE("Mode1: Extract PTX via cuobjdump", "[mode1][extract]") {
    std::string ptx = extract_ptx_cuobjdump(TEST_BINARY);
    CHECK_FALSE(ptx.empty());
    INFO("Extracted " << ptx.size() << " bytes");
}

TEST_CASE("Mode1: Parse PTX structure", "[mode1][parse]") {
    std::string ptx = extract_ptx_cuobjdump(TEST_BINARY);
    if (ptx.empty()) SKIP("PTX extraction failed");

    bool has_entry = ptx_contains(ptx, ".entry");
    bool has_bar = ptx_contains(ptx, "bar.");
    bool has_shared = ptx_contains(ptx, ".shared") || ptx_contains(ptx, "ld.shared") || ptx_contains(ptx, "st.shared");

    INFO("entry: " << has_entry << ", barrier: " << has_bar << ", shared: " << has_shared);
    CHECK(has_entry);
}

TEST_CASE("Mode1: PTX contains expected instructions", "[mode1][verify]") {
    std::string ptx = extract_ptx_cuobjdump(TEST_BINARY);
    if (ptx.empty()) SKIP("PTX extraction failed");

    CHECK(ptx_contains(ptx, ".entry"));
    CHECK(ptx_contains(ptx, "bar.sync"));
}

TEST_CASE("Mode1: PTX structure validation", "[mode1][trace]") {
    init_factory_once();

    std::string ptx = extract_ptx_cuobjdump(TEST_BINARY);
    if (ptx.empty()) SKIP("PTX extraction failed");

    WarpContext warp;
    std::vector<std::unique_ptr<ThreadContext>> threads;
    setup_warp(warp, threads, 32);
    reset_warp(warp);
    warp.set_active_mask(0xFFFFFFFF);

    // 验证 PTX 包含预期指令关键字
    INFO("Mode1 PTX size: " << ptx.size() << " bytes");
    CHECK(ptx.size() > 100);
    CHECK(ptx.find("entry") != std::string::npos);
}
