/**
 * @file test_test_divergence_sync_standalone_mode3a.cpp
 * @brief Mode 3a: StatementContext BEFORE CFG
 *
 * Auto-generated by four-mode testing generator.
 * Uses parsed StatementContext BEFORE CFG builder runs.
 * Key difference from Mode 3b: reconvergence_pc is NOT yet set (-1).
 */

#include "catch_amalgamated.hpp"
#include "test_helpers.hpp"

#define TEST_MODE 3
#define TEST_NAME "test_divergence_sync_standalone"


TEST_CASE("Mode3a: test_divergence_sync_standalone - barrier via StatementContext (cta)", "[mode3a][barrier]") {
    init_factory_once();

    // 使用 StatementContext 构建 barrier 指令序列
    std::vector<StatementContext> stmts;
    stmts.push_back(make_bar_sync(0));
    stmts.push_back(make_exit());

    // 验证：BEFORE CFG，barrier 的 StatementContext 类型
    INFO("Statement count: " << stmts.size());
    CHECK(stmts.size() == 2);
    CHECK(stmts[0].type == S_BAR);

    // 执行 bar.sync 指令序列验证
    INFO("Barrier StatementContext verified (type=" << stmts[0].type << ")");
    CHECK(stmts[0].instructionText.find("bar") != std::string::npos);
}


TEST_CASE("Mode3a: test_divergence_sync_standalone - shared memory via StatementContext", "[mode3a][shared]") {
    init_factory_once();

    // 使用 StatementContext 构建 shared memory 指令序列
    std::vector<StatementContext> stmts;
    stmts.push_back(make_ld_shared("%r1", "shared_data", "%r0"));
    stmts.push_back(make_st_shared("shared_data", "%r0", "%r2"));
    stmts.push_back(make_exit());

    INFO("Statement count: " << stmts.size());
    CHECK(stmts.size() == 3);

    // 验证 ld.shared 指令
    CHECK(stmts[0].type == S_LD);
    CHECK(stmts[0].instructionText.find("ld.shared") != std::string::npos);

    // 验证 st.shared 指令
    CHECK(stmts[1].type == S_ST);
    CHECK(stmts[1].instructionText.find("st.shared") != std::string::npos);
}


TEST_CASE("Mode3a: test_divergence_sync_standalone - divergence via StatementContext", "[mode3a][divergence]") {
    init_factory_once();

    // 使用 StatementContext 构建分支指令序列
    std::vector<StatementContext> stmts;
    stmts.push_back(make_mov("%r1", "%tid.x"));
    stmts.push_back(make_setp_lt("%p1", "%r1", "16"));
    stmts.push_back(make_label("L_true"));
    stmts.push_back(make_add("%r2", "%r1", "1"));
    stmts.push_back(make_label("L_false"));
    stmts.push_back(make_mov_imm("%r2", -1));
    stmts.push_back(make_label("L_join"));
    stmts.push_back(make_exit());

    INFO("Statement count: " << stmts.size());
    CHECK(stmts.size() == 8);

    // 验证分支指令类型
    CHECK(stmts[1].type == S_SETP);
    CHECK(stmts[1].instructionText.find("setp.lt") != std::string::npos);

    // 验证 label 指令
    CHECK(stmts[2].type == S_LABEL);
    CHECK(stmts[2].instructionText.find("L_true") != std::string::npos);

    // BEFORE CFG: 分支 reconvergence_pc 应为 -1
    // (make_bra_pred 创建的分支默认 reconvergence_pc = -1)
    StatementContext bra = make_bra_pred("L_join", "%p1", false);
    CHECK(bra.type == S_BRA);
    const auto& bra_data = std::get<BranchInstr>(bra.data);
    INFO("reconvergence_pc before CFG: " << bra_data.reconvergence_pc);
    CHECK(bra_data.reconvergence_pc < 0);
}


// ============================================================================
// CFG comparison: Mode3a = BEFORE CFG, Mode3b = AFTER CFG
// Mode3a shows the raw parsed state (reconvergence_pc = -1)
// Mode3b shows the CFG-processed state (reconvergence_pc filled)
// ============================================================================

// ============================================================================
// Custom test cases - add your kernel-specific tests here
// ============================================================================
