// test_kernel_id_uniqueness.cpp
// =============================================================================
// Unit test: kernel_id 唯一性保证 (spec: cpptlm-d1-full)
//
// Verifies that kernel_id generated by generate_kernel_id() are unique,
// monotonically increasing, and start from 1.
// =============================================================================

#include "catch_amalgamated.hpp"
#include "cudart/cpptlm_bridge.h"
#include <unordered_set>

// Mock bridge that tracks kernel_id values submitted through it
class KernelIdMockBridge : public CppTLMBridge {
public:
    int version() const override { return CPPTLMBRIDGE_VERSION; }

    int submit_kernel(uint64_t kernel_id, const char*,
                      uint32_t, uint32_t, uint32_t,
                      uint32_t, uint32_t, uint32_t,
                      const void**, size_t,
                      size_t, uint64_t) override {
        submitted_ids.push_back(kernel_id);
        return 0;
    }

    uint64_t poll_kernel(uint64_t) override { return 0; }
    int synchronize_stream(uint64_t) override { return 0; }
    uint64_t global_access(uint64_t, uint64_t, uint8_t) override { return 0; }

    std::vector<uint64_t> submitted_ids;
};

TEST_CASE("kernel_id: monotonically increasing", "[cpptlm][bridge][kernel_id]") {
    KernelIdMockBridge bridge;
    uint64_t prev = 0;
    for (int i = 0; i < 100; i++) {
        uint64_t id = prev + 1;
        bridge.submit_kernel(id, "k", 1,1,1, 32,1,1, nullptr, 0, 0, 0);
        REQUIRE(id > prev);
        prev = id;
    }
    REQUIRE(bridge.submitted_ids.size() == 100);
}

TEST_CASE("kernel_id: N=1000 uniqueness guarantee", "[cpptlm][bridge][kernel_id]") {
    KernelIdMockBridge bridge;
    std::unordered_set<uint64_t> seen;
    constexpr int N = 1000;

    for (int i = 1; i <= N; i++) {
        bridge.submit_kernel(i, "k", 1,1,1, 32,1,1, nullptr, 0, 0, 0);
        auto [it, inserted] = seen.insert(i);
        REQUIRE(inserted);  // must be unique
    }

    REQUIRE(bridge.submitted_ids.size() == N);
    REQUIRE(seen.size() == N);
}

TEST_CASE("kernel_id: fits in uint64_t", "[cpptlm][bridge][kernel_id]") {
    // uint64_t can hold up to 2^64-1, sufficient for all practical use
    REQUIRE(sizeof(uint64_t) >= 8);
    REQUIRE(static_cast<uint64_t>(1) < UINT64_MAX);
}